BAD_WORDS_API_KEY=BAD_WORDS_API_KEY
PASETO_KEY="RANDOM WORDS WINTER MACINTOSH PC"
PORT=API_PORT

POSTGRES_USER=postgres
POSTGRES_PASSWORD=password

POSTGRES_DB=rustwebdev
POSTGRES_HOST=localhost
# POSTGRES_PORT=5432
POSTGRES_PORT=POSTGRESQL_LISTENING_PORT

RUST_LOG=debug
