version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      # - "5432:5432"
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - rust-web
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - rust-web
      # - default
    ports:
      - "3030:3030"

volumes:
  data:

networks:
  rust-web:
    driver: bridge
